### PR TITLE
Revert concurrency target to default Knative value

### PR DESCRIPTION
**Pull request by leokondrashov**
## Summary

Revert to default knative values for target concurrency (100% -> 70%). This would mean that autoscaler would set function scale so estimated utilization of it would be approximately 70%.

Full utilization of concurrency made system prone to fast scale ups due to variations in load. This change would make the system more stable and closer to what is expected from production system.

## Implementation Notes :hammer_and_pick:

Remove setting it in the function configuration, better to reuse default one set on the global level.

## External Dependencies :four_leaf_clover:

* N/A

## Breaking API Changes :warning:

* N/A

### CODE REVIEW

**Comment by leokondrashov** [comment]
@cvetkovic, what's you view on that?

**Comment by cvetkovic** [comment]
> @cvetkovic, what's you view on that?

I and @Lightxyz think that you can proceed with merging. Just rebase and rerun unit tests.

**Review by cvetkovic — APPROVED** [review]

**Comment by ustiugov** [comment]
@cvetkovic @leokondrashov please don't use merge commits, please update by rebasing

**Comment by leokondrashov** [comment]
Actually, this merge commit didn't make it into the main branch, so history is still clean

**Pull request merged**
